version: '3.3'

services:
  python:
    container_name: python
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TG_TOKEN=${TG_TOKEN}
      - TG_CHANNEL=${TG_CHANNEL}
      - VK_TOKEN=${VK_TOKEN}
      - VK_API_VERSION=${VK_API_VERSION}